### ISSUE TITLE
httpclient dependency issue with Ruby 2.3.0

### ISSUE THREAD

**Issue by kapso** [AfterShip/aftership-sdk-ruby#17]
Any plans of upgrading the dependent version of `httpclient` ??

The current version gives this warning in Ruby 2.3.0 - 

/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:762:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.

**Comment by kapso** [comment]
Hey guys, any plans of fixing this?

**Comment by Bossa573** [comment]
Sorry for the delayed response, we released version `4.3.1` with `httpclient 2.7.1` which should solve the mentioned issue, thanks for reporting
