### ISSUE TITLE
Update httpclient dependency to ~> 2.8.3

### ISSUE THREAD

**Issue by brentmulligan** [AfterShip/aftership-sdk-ruby#29]
Hi, 

Any plans to upgrade dependency on httpclient to httpclient 2.8.3 ([change log](https://github.com/nahi/httpclient/blob/master/CHANGELOG.md))

The current dependency on httpclient ~> 2.7.1 is causing conflicts with other gems that depend on the newer version.

Thanks,
Brent

**Comment by brentmulligan** [comment]
Hi, I just wanted to follow up on this? Thanks

**Comment by Bossa573** [comment]
thanks for the reporting, this will be replaced by https://github.com/AfterShip/aftership-sdk-ruby/pull/33

**Comment by Bossa573** [comment]
This one should be resolved with version 4.5.1

**Comment by brentmulligan** [comment]
Thanks!
