### ISSUE TITLE
TLS v 1.2

### ISSUE THREAD

**Issue by msalo3** [AfterShip/aftership-sdk-ruby#30]
Hi, I wanted to check to see if this gem is configured to use TLS v1.2

Aftership is no longer allowing any TLS version below 1.2. See here: https://help.aftership.com/hc/en-us/articles/360048857374-AfterShip-secures-connections-with-TLS-1-2-and-above

Thanks!

**Comment by Bossa573** [comment]
thanks for the reporting, this issue will be handled by https://github.com/AfterShip/aftership-sdk-ruby/pull/33

**Comment by Bossa573** [comment]
This one should be resolved with version 4.5.1
